ulo/config/urls.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------
# standard library imports

# core django imports
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

# thrid party app imports

# project imports
from generics.views import HomeView, NavigationView,  SearchView
from users.views import LoginView, LogoutView, SignUpView


# TO SERVE MEDIA FILE IN DEVELOPMENT ONLY
from django.conf.urls.static import static


# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Landing Page
	url(r'^$', HomeView.as_view(), name='home'),
	# Search Page
	url(r'^search/$', SearchView.as_view(), name='search'),
	url(r'^search/', include('generics.urls', namespace='generics')),


	# User Posts (Post detail, Post form)
	url(r'^post/', include('posts.urls', namespace='posts')),
	# User Pages (Profile, Profile update)
	url(r'^user/', include('users.urls', namespace='users')),
	# User Comments
	url(r'^comment/', include('comments.urls', namespace='comments')),

	# Sign Up Page
	url(r'^signup/$', SignUpView.as_view(), name='signup'),
	# Login Page
	url(r'^login/(\?redirect_to=(?P<redirect_to>[^<>\'"@]*/))?$', 
		LoginView.as_view(), name='login'),
	# Logout Url
	url(r'^logout/$', LogoutView.as_view(), name='logout'),
	
	# Accounts Settings
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
	# User Settings
	url(r'^settings/', include('settings.urls', namespace='settings')),

	# Admin web interface
	url(r'^admin/', include(admin.site.urls)),

	# Error views
	url(r'^500/$', 'django.views.defaults.server_error', name='server_error'),

	# Dedicated site navigation when js is disabled.
	url(r'^navigation/$', NavigationView.as_view(), name='navigation'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ----------------------------------------------------------------------------------------

ulo/posts/urls.py
"""
Accounts URL Configuration
The `urlpatterns` list routes URLs to views.
"""
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------
# standard library imports
from __future__ import unicode_literals

# core django imports
from django.conf.urls import include, url

# thrid party app imports

# project imports
from . import views

# ----------------------------------------------------------------------------------------


urlpatterns = [

	# Post Form
	url(r'^$', views.PostFormView.as_view(), name='form'),
	# post only requests for videos
	url(r'^video/$', views.PostVideoFormView.as_view(), name='video_form'),

	url(r'^all/$', views.PostListView.as_view(), name='test'),

	# Users Post
	url(r'^(?P<pk>[\d]+)/$', views.PostView.as_view(), name='post'),
	url(r'^(?P<pk>[\d]+)/edit/$', views.PostEditView.as_view(), name='post_edit'),

	# Vote on a post
	url(r'^vote/$', views.PostVoteView.as_view(), name='vote'),


	# Post actions menu when JS is disabled
	url(r'^(?P<pk>[\d]+)/actions/$', views.PostActionsView.as_view(), name='actions'),
	# User reporting issue with post
	url(r'^report/complete/$', views.PostReportCompleteView.as_view(), name='report_complete'),
	url(r'^report/(?P<pk>[\d]+)/$', views.PostReportView.as_view(), name='report'),


]

# ----------------------------------------------------------------------------------------

ulo/posts/models.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------
# standard library imports
from __future__ import unicode_literals

# core django imports
from django.conf import settings
from django.core import validators
from django.db import models
from django.utils import timezone
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_text
from django.utils.translation import ugettext_lazy as _


# thrid party app imports

# project imports
from .utils import (
	CATEGORIES, COMMENT_SETTINGS, DISLIKE_CHAR, ENABLED, IMAGE, LIKE_CHAR, MEDIA_TYPES, 
	POST_REPORTS, VOTE_CHARS
)

# ----------------------------------------------------------------------------------------

class Post(models.Model):
	
	def file_path(self, filename):
		"""
		Create file path for the images/video in the user's post
		"""
		return 'posts/%s/%s' %(timezone.now().strftime("%m-%y"), filename)

	# POST (REQUIRED) FIELDS
	# ------------------------------------------------------------------------------------
	upload0 = models.FileField(
		_('add photos or video'),
		upload_to=file_path,
		default='default/post.jpg',
	)
	title = models.CharField(
		_('title'), 
		max_length=100, 
		blank=False,
		help_text=_('Title your post.'),
	)
	vote0 = models.CharField(
		_('option one'),
		max_length=30,
		choices=VOTE_CHARS,
		default=LIKE_CHAR,
		help_text=_('Select vote options one.'),
	)
	vote1 = models.CharField(
		_('option two'),
		max_length=30,
		choices=VOTE_CHARS,
		default=DISLIKE_CHAR,
		help_text=_('Select vote options two.'),
	)

	# END POST (REQUIRED) FIELDS
	# ------------------------------------------------------------------------------------


	# POST (OPTIONAL) FIELDS
	# ------------------------------------------------------------------------------------
	
	category = models.PositiveSmallIntegerField(
		_('categories'), 
		choices=CATEGORIES,
		blank=True,
		null=True,
		help_text=_('Categorize your post for better search results.'),
	)
	# VARCHAR is faster when searching the entire contents of a field
	tags = models.CharField(
		_('hash tags'), 
		max_length=400,
		blank=True,
		help_text=_('E.g. #London #Summer #PhotoOfTheDay'),
	)
	# VARCHAR is faster when searching the entire contents of a field
	description = models.CharField(
		_('description'), 
		max_length=600,
		blank=True,
		help_text=_('Tell others what your post is about.'),
	)

	# END POST (OPTIONAL) FIELDS
	# ------------------------------------------------------------------------------------


	# SETTINGS FIELDS
	# ------------------------------------------------------------------------------------
	
	comment_settings = models.PositiveSmallIntegerField(
		_('comment settings'),
		choices=COMMENT_SETTINGS,
		default=ENABLED
	)

	# location = models.CharField(
	# 	_('location'),
	# 	max_length=200,
	# 	blank=True,
	# 	help_text=_('Add a location to your post.'),
	# )

	# views = models.BigIntegerField(
	# 	_('views'),
	# 	blank=False,
	# 	default=0,
	# )

	# END SETTINGS FIELDS
	# ------------------------------------------------------------------------------------


	# ACCESS FIELDS
	# ------------------------------------------------------------------------------------
	
	is_removed = models.BooleanField(
		_('post removed'),
		default=False,
		help_text=_('This post has been removed due to reports of misconduct.'),
	)
	
	# END ACCESS FIELDS
	# ------------------------------------------------------------------------------------


	# INFO FIELDS
	# ------------------------------------------------------------------------------------
	published = models.DateTimeField(
		_('published'), 
		default=timezone.now,
	)
	# views = models.BigIntegerField(
	# 	_('views'),
	# 	default=0
	# )
	# media_type = models.PositiveSmallIntegerField(
	# 	_('media type'),
	# 	choices=MEDIA_TYPES,
	# 	default=IMAGE
	# )
	# END INFO FIELDS
	# ------------------------------------------------------------------------------------
	

	# DB RELATIONSHIPS
	# ------------------------------------------------------------------------------------
	
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

	### Post has a one-to-many relations with PostReport.
	### Post has a one-to-many relations with PostVote.
	### Post has a one-to-many relations with Comment.

	# END DB RELATIONSHIPS
	# ------------------------------------------------------------------------------------


	class Meta:
		verbose_name = _('post')
		verbose_name_plural = _('posts')
		ordering = ['-published']

	def __str__(self):
		return self.user.username+': '+self.title


# ----------------------------------------------------------------------------------------

class PostVote(models.Model):

	# POSTVOTE (REQUIRED) FIELDS
	# ------------------------------------------------------------------------------------
	vote = models.PositiveSmallIntegerField(
		_('vote')
	)
	# END POSTVOTE (REQUIRED) FIELDS
	# ------------------------------------------------------------------------------------

	# INFO FIELDS
	# ------------------------------------------------------------------------------------
	# published = models.DateTimeField(
	# 	_('published'), 
	# 	default=timezone.now,
	# )
	# END INFO FIELDS
	# ------------------------------------------------------------------------------------


	# DB RELATIONSHIPS
	# ------------------------------------------------------------------------------------

	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

	# END DB RELATIONSHIPS
	# ------------------------------------------------------------------------------------


	class Meta:
		verbose_name = _('post vote')
		verbose_name_plural = _('post votes')
		unique_together = ('post', 'user')

	def __str__(self):
		return str(self.vote)


# ----------------------------------------------------------------------------------------

class PostReport(models.Model):
	"""
	Report abuse found in a post.
	"""

	# POSTREPORT (REQUIRED) FIELDS
	# ------------------------------------------------------------------------------------
	report = models.PositiveSmallIntegerField(
		_('report'),
		choices=POST_REPORTS,
		help_text=_('What is wrong with this post?')
	)
	# END POSTREPORT (REQUIRED) FIELDS
	# ------------------------------------------------------------------------------------


	# POSTREPORT (OPTIONAL) FIELDS
	# ------------------------------------------------------------------------------------
	information = models.TextField(
		_('additional information'),
		max_length=400,
		blank=True,
		help_text=_('Please provide any additional information that will help us resolve '
			'the issue.')
	)
	# END POSTREPORT (OPTIONAL) FIELDS
	# ------------------------------------------------------------------------------------


	# INFO FIELDS
	# ------------------------------------------------------------------------------------
	published = models.DateTimeField(
		_('published'), 
		default=timezone.now,
	)
	# END INFO FIELDS
	# ------------------------------------------------------------------------------------


	# DB RELATIONSHIPS
	# ------------------------------------------------------------------------------------

	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

	# END DB RELATIONSHIPS
	# ------------------------------------------------------------------------------------


	class Meta:
		verbose_name = _('post report')
		verbose_name_plural = _('post reports')

	def __str__(self):
		return self.post.title+': '+self.report+' (by: '+self.user.username+')'


# ----------------------------------------------------------------------------------------

ulo/posts/forms.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------
# standard library imports
from __future__ import unicode_literals
from PIL import Image

# core django imports
from django import forms
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _

# thrid party app imports

# project imports
from .models import Post, PostReport
from ulo.forms import UloModelForm, UloSecureModelForm
from ulo.handlers import get_error

from posts.search import create_post, update_post
from posts.utils import POST_REPORTS

# USER UPLOAD FORMS
# ----------------------------------------------------------------------------------------

class PostForm(UloModelForm):

	tags = forms.CharField(required=False, widget=forms.Textarea())
	description = forms.CharField(required=False, widget=forms.Textarea())

	class Meta:
		model = Post
		fields = ('title', 'vote0', 'vote1', 'category', 'tags', 'description', 
			'comment_settings', 'upload0')
		

	def __init__(self, *args, **kwargs):
		"""
		"""
		self.request = kwargs.pop('request', None)
		super(PostForm, self).__init__(*args, **kwargs)
		self.unknown_error = ('We could not create your post at this moment in time. '
			'Please try again later, we are looking into the problem.')

		# Add field specific attributes
		self.fields['title'].widget.attrs.update({
			'autofocus': 'autofocus',
		})
		# Add capture functionality to image uploads
		self.fields['upload0'].widget.attrs.update({
			'accept': 'image/gif,image/jpeg,image/jpg,image/png,video/*',
			'capture': 'capture',
			'multiple': 'multiple'
		})

	def is_valid(self):
		if not self.files:
			error = get_error(self.request) or _('Please upload photos or a video.')
			self.add_error('upload0', error)

		return super(PostForm, self).is_valid()

	def save(self, commit=True):
		# assign the user to the post instance being created
		self.instance.user = self.request.user
		post = super(PostForm, self).save(commit=False)
		if commit:
			# will return None if the post or elasticsearch doc was not created.
			post = create_post(post, self.request.user)
		return post

# ----------------------------------------------------------------------------------------

class PostEditForm(UloSecureModelForm):

	class Meta:
		model = Post
		fields = ('title', 'category', 'tags', 'description')

	def __init__(self, *arg, **kwargs):
		super(PostEditForm, self).__init__(*arg, **kwargs)
		# UloSecureModelForm requires self.instance to be a user object or self.user to be 
		# set to check the user's password.
		self.user = self.instance.user

	@cached_property
	def changed_data(self):
		"""
		Generate a list of changed field. This is a case insensitive, simplified version 
		of Django's own changed_data. 
		https://docs.djangoproject.com/en/1.9/_modules/django/forms/forms/#Form
		"""
		changed = []
		for name, field in self.fields.items():

			try:
				data = self.cleaned_data.get(name, '')
				data = data.lower()
			except AttributeError:
				pass

			if field.has_changed(self.initial.get(name, field.initial), data):
				changed.append(name)
				
		return changed

	def save(self, commit=True):
		"""
		Save changes and send verification email to the user if they changed their 
		emails address. NOTE: UloSecureModelForm stored the instance variable as
		instance_copy. See ulo.formmixins.UloBaseModelFormMixin for full explanation.
		"""

		post = super(PostEditForm, self).save(commit=False)
		
		if commit:
			# update elasticsearch and save post to db
			post = update_post(post, self.changed_data)

		return post

# ----------------------------------------------------------------------------------------

class PostReportForm(UloModelForm):

	post_id = forms.CharField(
		widget=forms.HiddenInput(),
		error_messages={
			'required': _('We could not determine which post you are looking to report.')
		}
	)

	report = forms.ChoiceField(
		widget=forms.RadioSelect(),
		initial=0, 
		choices=POST_REPORTS,
		help_text=_('What is wrong with this post?'),
	)

	class Meta:
		model = PostReport
		fields = ('report', 'information')

	def __init__(self, *args, **kwargs):
		self.user_id = kwargs.pop('user_id', None)
		super(PostReportForm, self).__init__(*args, **kwargs)

	def save(self, commit=True):
		# assign the user and post ids to the PostReport instance being created
		self.instance.post_id = self.cleaned_data['post_id']
		self.instance.user_id = self.user_id
		return super(PostReportForm, self).save(commit=commit)

# ----------------------------------------------------------------------------------------

ulo/templates/posts/actions.html
{% extends "base.html" %}
{% load staticfiles i18n %}


{% block title %}Post actions{% endblock title %}


{% block content %}

	<a href="{% url 'posts:post' post.pk %}">back to post</a>

	<div>{{ post.title }}</div>
	<img src="{% static post.upload0.url %}" style="width:200px; height:200px">

	<ul>
		<li><a href="#share">Share</a></li>
		<li><a href="#report">Report</a></li>
	</ul>

	<br><br>
	<div id="share">
		<h1>Share</h1>
	</div>
	<br><br>
	<div id="report">
		<h1>Report</h1>
		<form action="{% url 'posts:report' post.pk %}" method="post">
			{% csrf_token %}
			{{ form.post_id }}

			<div>
				<p>{{ form.report.errors }}</p>
				<p>{{ form.report.help_text }}</p>
				{{ form.report }}
			</div>

			<div>
				<p>{{ form.information.errors }}</p>
				<p>{{ form.information.help_text }}</p>
				{{ form.information }}
			</div>

		<input id="id_submit" name="submit" type="submit" value="Report">
	</form>
	</div>
	

{% endblock content %}

ulo/templates/posts/all.html
{% extends "base.html" %}
{% load staticfiles i18n %}


{% block title %}All{% endblock title %}


{% block content %}

	{% for post in posts %}
		<div>
			<div>{{ post.title }}</div>
			<img src="{% static post.upload0.url %}" style="width:100px; height:100px" >
			<div>{{ post.vote0 }}</div>
			<div>{{ post.vote1 }}</div>
		</div>
		<br><br>
	{% endfor %}

{% endblock content %}

ulo/templates/posts/post.html
{% extends "base.html" %}
{% load staticfiles i18n %}


{% block title %}Ulo{% endblock title %}


{% block content %}
	<h1>Post</h1>

	<p>U+1F601 &#x1F601;</p>

	<div>{{ post.title }}</div>
	<img src="{% static post.upload0.url %}" style="width:200px; height:200px">
	
	<form action="{% url 'posts:vote' %}" method="post">
		{% csrf_token %}
		<input type="hidden" name="post_id" value="{{ post.pk }}">
		<button type="submit" name="vote" value="{{vote0_value}}">{{ post.vote0 }}</button>
		<span>{{ votes.1 }}</span>
		<button type="submit" name="vote" value="{{vote1_value}}">{{ post.vote1 }}</button>
		<span>{{ votes.2 }}</span>

		<div>User Vote: {{ user_vote.0 }}</div>

	</form>


	<div>{{ post.user.name }}</div>
	<div>{{ post.user.username }}</div>

	<a id="sub" href="{% url 'posts:actions' post.pk %}">Post Actions</a>

	<div>
		<form id="comment_form" action="{% url 'comments:post' %}" method="post">
			{% csrf_token %}
			{{ form.http_referer }}

			<label>{{ form.text.label }}</label>
			{{ form.text }}
			<input name="post_id" type="hidden" value="{{post.pk}}">
			<input id="id_submit" disabled name="submit" type="submit" value="Comment">
		</form>
	</div>

	<div>{{ cvs }}</div>

	<div>
		{% for comment in comments %}
			<div><img src="{% static comment.user.picture.url %}"></div>
			<div>{{ comment.published|timesince }} ago</div>
			<div>{{ comment.user.username }}</div>
			<div>{{ comment.text }}</div>
			<form action="{% url 'comments:vote' %}" method="post">
				{% csrf_token %}
				<input type="hidden" name="comment_id" value="{{ comment.pk }}">
				<button type="submit" name="vote">Agree</button>
			</form>
			<div>User Comment Vote: {{ comment.vote.0 }}</div>
			<a href="{% url 'comments:report' comment.pk %}">Comment Actions</a>
			<br><br>
		{% endfor %}
	</div>


{% endblock content %}

{% block js_pg %}
  <!-- profile page javascript file -->
  <script src="{% static 'js/comments/comment.js' %}"></script>
{% endblock js_pg %}

ulo/templates/posts/post_edit.html
{% extends "base.html" %}
{% load staticfiles i18n %}


{% block title %}Post Edit{% endblock title %}


{% block content %}

	<!-- Post Form -->
	<form id="post_edit_form" action="{% url 'posts:post_edit' pk %}" method="post" >
		<!-- cross site request forgery protection -->
		{% csrf_token %}

		{{ form.errors }}

		<!-- Required Fields -->
		<div>
 
			<div id="title_container">
				<label for="id_title">{{ form.title.label }}</label>
				{{ form.title }}
			</div>


		<!-- End Required Fields -->

		<!-- Optional Fields / Settings -->
		<div>
			<div id="category_container">
				<label for="id_category">{{ form.category.label }}</label>
				{{ form.category }}
			</div>
			<div id="tags_container">
				<label for="id_tags">{{ form.tags.label }}</label>
				{{ form.tags }}
			</div>
			<div id="description_container">
				<label for="id_category">{{ form.description.label }}</label>
				{{ form.description }}
			</div>
			<div id="comment_settings_container">
				<label for="id_comment_settings">{{ form.comment_settings.label }}</label>
				{{ form.comment_settings }}
			</div>

		</div>
		<!-- End Optional Fields / Settings -->

		<div id="submit_container">
			{{ form.password.label }}
			{{ form.password }}
			<input id="id_submit" name="submit" type="submit" value="Edit">
		</div>

	</form>
    <!-- END Post Form -->

{% endblock content %}

{% block js_pg %}
{% endblock js_pg %}

ulo/templates/posts/post_form.html
{% extends "base.html" %}
{% load staticfiles i18n %}


{% block title %}Ulo Post{% endblock title %}


{% block content %}
	
	<noscript>Enable Javascript to make a post!</noscript>

	<!-- Post Form -->
	<form id="post_form" action="{% url 'posts:form' %}" method="post" enctype="multipart/form-data">
		<!-- cross site request forgery protection -->
		{% csrf_token %}

		{{ form.errors }}

		<!-- Required Fields -->
		<div>
 
			<div id="title_container">
				<label for="id_title">{{ form.title.label }}</label>
				{{ form.title }}
			</div>

			<div id="upload0_container">
				<div id="upload_controls" class="equal_width"></div>      
				<div id="editor_content" class="ratio_container">
					<div class="ratio_spacer"></div>
					<div class="ratio">
						<div id="upload_target" class="equal_width"></div>
					</div>
				</div>
			</div>
			<label for="id_upload0">{{ form.upload0.label }}</label>
			

			<div id="votes_container">
				<div id="vote0_container">
					<label for="id_vote0">{{ form.vote0.label }}</label>
					{{ form.vote0}}
				</div>
				<div id="vote1_container">
					<label for="id_vote1">{{ form.vote1.label }}</label>
					{{ form.vote1}}
				</div>
			</div>

		</div>
		<!-- End Required Fields -->

		<!-- Optional Fields / Settings -->
		<div>
			<div id="category_container">
				<label for="id_category">{{ form.category.label }}</label>
				{{ form.category }}
			</div>
			<div id="tags_container">
				<label for="id_tags">{{ form.tags.label }}</label>
				{{ form.tags }}
			</div>
			<div id="description_container">
				<label for="id_category">{{ form.description.label }}</label>
				{{ form.description }}
			</div>
			<div id="comment_settings_container">
				<label for="id_comment_settings">{{ form.comment_settings.label }}</label>
				{{ form.comment_settings }}
			</div>

		</div>
		<!-- End Optional Fields / Settings -->

		{{ form.upload0 }}
		<div id="submit_container">
			<input id="id_submit" name="submit" type="button" value="Post">
		</div>

	</form>
    <!-- END Post Form -->

{% endblock content %}

{% block page_js %}
  <!-- profile page javascript file -->
  <script src="{% static 'js/posts/post_form.js' %}"></script>
{% endblock page_js %}

ulo/templates/posts/report.html
{% extends "base.html" %}
{% load staticfiles i18n %}


{% block title %}Report{% endblock title %}


{% block content %}
	
	{% firstof form.non_field_errors form.post_id.errors %}

	<form method="post">
		{% csrf_token %}
		{{ form.post_id }}

		<div>
			<p>{{ form.report.errors }}</p>
			<p>{{ form.report.help_text }}</p>
			{{ form.report }}
		</div>

		<div>
			<p>{{ form.information.errors }}</p>
			<p>{{ form.information.help_text }}</p>
			{{ form.information }}
		</div>

		<input id="id_submit" name="submit" type="submit" value="Report">
	</form>

{% endblock content %}

ulo/templates/posts/report_complete.html
{% extends "base.html" %}
{% load staticfiles i18n %}


{% block title %}Report{% endblock title %}


{% block content %}
	
	<h1>Thank you for your report</h1>
	
	<p>If we find the content to be in violation of our rules, we will take the necessary course of action.</p>

{% endblock content %}