ulo/accounts/urls.py
"""
Accounts URL Configuration
The `urlpatterns` list routes URLs to views.
"""
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------
# standard library imports
from __future__ import unicode_literals

# core django imports
from django.conf.urls import include, url

# thrid party app imports

# project imports
from . import views

# ----------------------------------------------------------------------------------------


urlpatterns = [

	# Email verification
	url(r'^verification/(?P<token>[^<>\'"@]+)/$',
		views.EmailVerificationView.as_view(), name='verification'),
	url(r'^resend_verification/$',
		views.ResendEmailVerificationView.as_view(), name='resend_verification'),

	# Password reset
	url(r'^password_reset/$', 
		views.UserAccountView.as_view(), name='user_account'),
	url(r'^password_reset/email/$', 
		views.PasswordResetEmailView.as_view(), name='password_reset_email'),
	url(r'^password_reset/sent/$', 
		views.PasswordResetSentView.as_view(), name='password_reset_sent'),
	url(r'^password_reset/(?P<token>[^<>\'"@]+)/$',
		views.PasswordResetFormView.as_view(), name='password_reset_form'),

	url(r'^not_my_account/confirmed/$',
		views.NotMyAccountConfirmedView.as_view(), name='not_my_account_confirmed'),
	url(r'^not_my_account/not_registered/$',
		views.NotMyAccountNoUserView.as_view(), name='not_my_account_no_user'),
	url(r'^not_my_account/(?P<token>[^<>\'"@]+)/$',
		views.NotMyAccountView.as_view(), name='not_my_account'),
	

	# Token expired
	url(r'^expired/$', 
		views.LinkExpiredView.as_view(), name='expired'),
	# Account deactivated
	url(r'^deactivated/$', 
		views.DeactivatedAccountView.as_view(), name='deactivated'),
]

# ----------------------------------------------------------------------------------------

ulo/config/urls.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------
# standard library imports

# core django imports
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

# thrid party app imports

# project imports
from generics.views import HomeView, NavigationView,  SearchView
from users.views import LoginView, LogoutView, SignUpView


# TO SERVE MEDIA FILE IN DEVELOPMENT ONLY
from django.conf.urls.static import static


# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Landing Page
	url(r'^$', HomeView.as_view(), name='home'),
	# Search Page
	url(r'^search/$', SearchView.as_view(), name='search'),
	url(r'^search/', include('generics.urls', namespace='generics')),


	# User Posts (Post detail, Post form)
	url(r'^post/', include('posts.urls', namespace='posts')),
	# User Pages (Profile, Profile update)
	url(r'^user/', include('users.urls', namespace='users')),
	# User Comments
	url(r'^comment/', include('comments.urls', namespace='comments')),

	# Sign Up Page
	url(r'^signup/$', SignUpView.as_view(), name='signup'),
	# Login Page
	url(r'^login/(\?redirect_to=(?P<redirect_to>[^<>\'"@]*/))?$', 
		LoginView.as_view(), name='login'),
	# Logout Url
	url(r'^logout/$', LogoutView.as_view(), name='logout'),
	
	# Accounts Settings
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
	# User Settings
	url(r'^settings/', include('settings.urls', namespace='settings')),

	# Admin web interface
	url(r'^admin/', include(admin.site.urls)),

	# Error views
	url(r'^500/$', 'django.views.defaults.server_error', name='server_error'),

	# Dedicated site navigation when js is disabled.
	url(r'^navigation/$', NavigationView.as_view(), name='navigation'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ----------------------------------------------------------------------------------------

ulo/posts/urls.py
"""
Accounts URL Configuration
The `urlpatterns` list routes URLs to views.
"""
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------
# standard library imports
from __future__ import unicode_literals

# core django imports
from django.conf.urls import include, url

# thrid party app imports

# project imports
from . import views

# ----------------------------------------------------------------------------------------


urlpatterns = [

	# Post Form
	url(r'^$', views.PostFormView.as_view(), name='form'),
	# post only requests for videos
	url(r'^video/$', views.PostVideoFormView.as_view(), name='video_form'),

	url(r'^all/$', views.PostListView.as_view(), name='test'),

	# Users Post
	url(r'^(?P<pk>[\d]+)/$', views.PostView.as_view(), name='post'),
	url(r'^(?P<pk>[\d]+)/edit/$', views.PostEditView.as_view(), name='post_edit'),

	# Vote on a post
	url(r'^vote/$', views.PostVoteView.as_view(), name='vote'),


	# Post actions menu when JS is disabled
	url(r'^(?P<pk>[\d]+)/actions/$', views.PostActionsView.as_view(), name='actions'),
	# User reporting issue with post
	url(r'^report/complete/$', views.PostReportCompleteView.as_view(), name='report_complete'),
	url(r'^report/(?P<pk>[\d]+)/$', views.PostReportView.as_view(), name='report'),


]

# ----------------------------------------------------------------------------------------

ulo/users/urls.py
"""
Accounts URL Configuration
The `urlpatterns` list routes URLs to views.
"""
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------
# standard library imports
from __future__ import unicode_literals

# core django imports
from django.conf.urls import include, url

# thrid party app imports

# project imports
from . import views

# ----------------------------------------------------------------------------------------


urlpatterns = [

	# UnFollow User
	url(r'^available/(?P<username>[\w]+)/$', views.UsernameAvailableView.as_view(), name='available'),

	# User Profile Edit Page
	url(r'^update/$', views.ProfileUpdateView.as_view(), name='profile_update'),
	# User Profile Page: username regex pattern used in users.models.User
	url(r'^(?P<username>[\w]+)/$', views.ProfileView.as_view(), name='profile'),

	# View User Followers
	url(r'^(?P<username>[\w]+)/followers/$', 
		views.FollowersView.as_view(), name='followers'),
	# View User Following
	url(r'^(?P<username>[\w]+)/following/$', 
		views.FollowingView.as_view(), name='following'),

	# Follow User
	url(r'^follow/(?P<pk>[\d]+)/$', 
		views.FollowUserView.as_view(), name='follow'),
	# UnFollow User
	url(r'^unfollow/(?P<pk>[\d]+)/$', 
		views.UnFollowUserView.as_view(), name='unfollow'),


	
	
]

# ----------------------------------------------------------------------------------------

ulo/users/models.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------
# standard library imports
from __future__ import unicode_literals

# core django imports
from django.contrib.auth import get_user_model
from django.contrib.auth.backends import ModelBackend
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import (
	AbstractBaseUser, BaseUserManager, PermissionsMixin
)
from django.core import validators
from django.db import models
from django.utils import timezone
from django.utils.crypto import salted_hmac
from django.utils.encoding import force_text
from django.utils.translation import ugettext_lazy as _


# thrid party app imports

# project imports
from .utils import BLOCK_TYPES, GENDERS, NO_BLOCK, NO_GENDER, NOT_VERIFIED


# ----------------------------------------------------------------------------------------

class UserModelBackend(ModelBackend):

	"""
	User authentication backend.
	https://docs.djangoproject.com/en/1.9/topics/auth/customizing/#auth-custom-user
	If a backend raises a PermissionDenied exception, authentication will immediately 
	fail. Django will not check the backends that follow.
	"""

	# return the User object if found or None
	def authenticate(self, email=None, password=None, **kwargs):

		UserModel = get_user_model()
		if email is None:
			email = kwargs.get(UserModel.USERNAME_FIELD)
		
		try:
			# natural key will be the field defined by the 'USERNAME_FIELD'
			user = UserModel._default_manager.get_by_natural_key(email)

			if user.check_password(password):
				return user

		except UserModel.DoesNotExist:
			# Run the default password hasher to reduce the timing difference between 
			# an existing and a non-existing user (#20760).
			UserModel().set_password(password)

# ----------------------------------------------------------------------------------------

class UserManager(BaseUserManager):

	def _create_user(
			self, email, username, name, password, **extra_fields):
		"""
		Create a new user.
		"""
		# check all required inputs are present
		if not email or not username or not name or not password:
			raise ValueError('Required fields missing. User was not created')
		# create user
		user = self.model(
			email=email.strip().lower(), 
			username=username.strip().lower(), 
			name=name.strip(),
 			**extra_fields
		)
		# hash password
		user.set_password(password)
		# save user to database and return the created user object
		user.save(using=self._db)
		return user

	# Must list all required fields as parameters to this function
	def create_user(self, email, username, name, password, **extra_fields):
		"""
		Create a new user.
		"""
		extra_fields.setdefault('is_staff', False)
		extra_fields.setdefault('is_superuser', False)
		return self._create_user(email, username, name, password, **extra_fields)


	# Must list all required fields as parameters to this function
	def create_superuser(self, email, username, name, password, **extra_fields):
		"""
		Create a new super user.
		"""
		extra_fields.setdefault('is_staff', True)
		extra_fields.setdefault('is_superuser', True)

		if extra_fields.get('is_staff') is not True:
			raise ValueError('Superuser must have is_staff=True.')
		if extra_fields.get('is_superuser') is not True:
			raise ValueError('Superuser must have is_superuser=True.')

		return self._create_user(email, username, name, password, **extra_fields)

# ----------------------------------------------------------------------------------------

class User(AbstractBaseUser, PermissionsMixin):
	
	def file_path(instance, filename):
		"""
		Create file path for the uploaded image
		"""
		return 'profile/%s/%s' %(timezone.now().strftime("%m-%y"), filename)

	# USER (REQUIRED) FIELDS
	# ------------------------------------------------------------------------------------
	
	# password is defined in AbstractBaseUser as:
	# password = models.CharField(_('password'), max_length=128)
	
	email = models.EmailField(
		_('email address'),
		max_length=255,
		unique=True,
		error_messages={
			'unique': _('This email address has already been registered.'),
		},
		help_text=_(
			'Please enter your email address.'
		),
	)
	username = models.CharField(
		_('username'),
		max_length=30,
		unique=True,
		validators=[
			validators.RegexValidator(
				r'^[\w]+$',
				_('Your username must consist of letters, numbers and underscores.'),
			),
		],
		error_messages={
			'unique': _('This username has been taken.'),
		},
		help_text=_(
			'Please choose a username. This can be changed later.'
		),
	)
	name = models.CharField(
		_('name'), 
		max_length=30, 
		validators=[
			validators.RegexValidator(
				r'^[^<>\[\](){}="`,\\/;:.+_|?!@#%^&*~±§]+$',
				_('Your name cannot contain special characters.')
			),
		],
		help_text=_(
			'The name displayed on your profile page.'
		),
	)
	dob = models.DateField(
		_('birthday'),
		help_text=_("Your date of birth."),
	)
	gender = models.CharField(
		_('gender'),
		max_length=1,
		choices=GENDERS,
		default=NO_GENDER,
	)


	# END USER (REQUIRED) FIELDS
	# ------------------------------------------------------------------------------------


	# USER (NOT REQUIRED) FIELDS
	# ------------------------------------------------------------------------------------
	picture = models.ImageField(
		_('picture'),
		upload_to=file_path,
		max_length=100, # default is 100
		default='default/profile.jpg',
		help_text=_("Profile picture."),
	)
	location = models.CharField(
		_('location'),
		max_length=200,
		validators=[
			validators.RegexValidator(
				r'^[^<>{}="`\\/;:.+_|?!@#%^&£$*~±§]+$',
				_('Your location cannot contain special characters.')
			),
		],
		blank=True,
		help_text=_("Your current location."),
	)
	blurb = models.CharField(
		_('blurb'),
		max_length=600,
		blank=True,
		help_text=_(
			'Short description about you, your page, or anything you wish to promote.'
		),
	)
	# END USER (NOT REQUIRED) FIELDS
	# ------------------------------------------------------------------------------------
	

	# ACCESS FIELDS
	# ------------------------------------------------------------------------------------
	is_staff = models.BooleanField(
		_('staff status'),
		default=False,
		help_text=_('Designates whether the user can log into this admin site.'),
	)
	is_active = models.BooleanField(
		_('active'),
		default=True,
		help_text=_(
			'Designates whether this user should be treated as active. '
			'Unselect this instead of deleting accounts.'
		),
	)
	is_verified = models.PositiveSmallIntegerField(
		_('email verified'),
		default=NOT_VERIFIED,
		help_text=_(
			'Designates whether this user has had their email address verified so that '
			'they are who they claim to be.'
		),
	)
	email_confirmed = models.BooleanField(
		_('email confirmation'),
		default=False,
		help_text=_(
			'Designates whether this user has confirmed thier email address.'
		),
	)

	block_type = models.CharField(
		_('account suspended'),
		max_length=1,
		choices=BLOCK_TYPES,
		default=NO_BLOCK,
		help_text=_(
			'Designates whether this has had their account suspended'
		),
	)
	# END ACCESS FIELDS
	# ------------------------------------------------------------------------------------


	# INFO FIELDS
	# ------------------------------------------------------------------------------------
	
	# last_login is defined in AbstractBaseUser as:
	# last_login = models.DateTimeField(_('last login'), blank=True, null=True)

	date_joined = models.DateTimeField(
		_('date joined'), 
		default=timezone.now,
	)
	# END INFO FIELDS
	# ------------------------------------------------------------------------------------


	# DB RELATIONSHIPS
	# ------------------------------------------------------------------------------------

	connections = models.ManyToManyField(
		'self', 
		symmetrical=False,
		through='Connection',
		through_fields=('from_user', 'to_user')
	)

	### User has a one-to-many relations with Post.
	### User has a one-to-many relations with PostReport.
	### User has a one-to-many relations with Comment.
	### User has a one-to-many relations with CommentVote.

	# END DB RELATIONSHIPS
	# ------------------------------------------------------------------------------------

	objects = UserManager()
	# The name of the field used as the unique identifier
	USERNAME_FIELD = 'email'
	# must contain all required fields and is used only when creating a super user.
	# These will be the fields that the user must enter (plus USERNAME_FIELD)
	REQUIRED_FIELDS = ['username', 'name', 'location']

	class Meta:
		verbose_name = _('user')
		verbose_name_plural = _('users')


	# HELPER FUNCTIONS
	# ------------------------------------------------------------------------------------

	def get_full_name(self):
		# The user is identified by their name
		return self.name

	def get_short_name(self):
		# The user is identified by their first name
		return self.name.partition(' ')[0]

	def is_blocked(self):
		return self.block_type != NO_BLOCK

	def get_block_message(self):
		return next(
			(desc for code, desc in BLOCK_TYPES if code==self.block_type),
			_('Your account has been suspended.')
		)

	def deactivate_account(self):
		self.is_active = False
		self.save()

	def get_absolute_url(self):
		from django.core.urlresolvers import reverse
		return reverse('users.views.UserProfile', args=[self.username])

	def is_following(self, user):
		return Connection.objects.filter(from_user=self, to_user=user).exists()

	def __str__(self):
		return self.email

	@property
	def is_staff(self):
		"Is the user a member of staff?"
		return self.is_admin

	def get_session_auth_hash(self):
		"""
		Return a HMAC of the password and blocked field. 
		This is a copy of Django's implementation with the addition of block_type to 
		invalidate sessions when users are blocked.
		https://github.com/django/django/blob/master/django/contrib/auth/base_user.py
		"""
		key_salt = 'users.models.User.get_session_auth_hash'

ulo/templates/users/followers.html
{% extends "base.html" %}
{% load staticfiles i18n %}


{% block title %}Followers of {{ user_profile.username }}{% endblock title %}


{% block content %}
	<h1>Followers</h1>
	
	{% for user in followers %}
		<div>
			<a href="{% url 'users:profile' user.from_user.username %}">
				<img src="{{ user.from_user.picture.url }}">
			</a>
			<a href="{% url 'users:profile' user.from_user.username %}">
				{{ user.from_user.name }}
			</a>
			<a href="{% url 'users:profile' user.from_user.username %}">
				{{ user.from_user.username }}
			</a>
		</div>
	{% endfor %}

	{{ paginate }}

{% endblock content %}

ulo/templates/users/following.html
{% extends "base.html" %}
{% load staticfiles i18n %}


{% block title %}Following {{ user_profile.username }}{% endblock title %}


{% block content %}
	<h1>Following</h1>

	
	{% for user in following %}
		<div>
			<a href="{% url 'users:profile' user.to_user.username %}">
				<img src="{{ user.to_user.picture.url }}">
			</a>
			<a href="{% url 'users:profile' user.to_user.username %}">
				{{ user.to_user.name }}
			</a>
			<a href="{% url 'users:profile' user.to_user.username %}">
				{{ user.to_user.username }}
			</a>
		</div>
	{% endfor %}

	{{ paginate }}

{% endblock content %}

ulo/templates/users/login.html
{% extends "base.html" %}
{% load staticfiles i18n %}


{% block page_head %}
	<title>Ulo Log In</title>
	<link href="{% static 'css/users/login.css' %}" rel="stylesheet" type="text/css">
{% endblock page_head %}


{% block content %}
<div id="login_form_wrapper">

	<div id="login_header">
		<h1 id="login_title">Welcome back</h1>
	</div>
	<div id="form_info">
	{% if form.non_field_errors %}
		<span class="error_icon"></span>
		<p class="nonfield">{{ form.non_field_errors.0 }}</p>
	{% endif %}
	</div>
	
	<form id="login_form" action="{% url 'login' %}{{ redirect_to }}" method="post">
		<!-- cross site request forgery protection -->
		{% csrf_token %}
		{{ form.redirect_to }}
		
		<div id="email_container">
			{{ form.email }}
		</div>
		<div id="password_container">
			{{ form.password }}
			<a id="forgot" href="{% url 'accounts:user_account' %}">Forgot?</a>
		</div>

		<div id="buttons_container">
			<div id="remember_container">
				{{ form.remember }}
				<label for="id_remember">Remember me<label>
			</div>
			<div id="submit_container" class="cf">
				<input id="id_submit" name="submit" type="submit" value="Log in">
			</div>
		</div>

	</form>
</div>

<div id="login_footer">
	<p class="link_text">Don't have an account? <a href="{% url 'signup' %}">Sign Up</a></p>
</div>

{% endblock content %}

{% block page_js %}
	<script src="{% static 'js/users/login.js' %}"></script>
{% endblock page_js %}

ulo/templates/users/profile.html
{% extends "base.html" %}
{% load staticfiles i18n %}


{% block page_head %}
	<title>Profile</title>
	<link href="{% static 'css/users/profile.css' %}" rel="stylesheet" type="text/css">
{% endblock page_head %}

{% block content %}
	<h1>User Profile Page</h1>

	{{ connections }}

	{% if user.is_authenticated and user == user_profile %}
		<a id="edit_profile" href="{% url 'users:profile_update' %}">Edit Profile</a>
	{% else %}

		{% if is_following %}
			<form action="{% url 'users:unfollow' user_profile.pk %}" method="post">
		{% else %}
			<form action="{% url 'users:follow' user_profile.pk %}" method="post">
		{% endif %}
			{% csrf_token %}
			<input type="hidden" name="http_referer" value="{{request.path_info|default_if_none:""}}">
			<input type="submit" value="{% if is_following %}Unfollow{% else %}Follow{% endif %}">
		</form>
	{% endif %}

	
	<div>
		<img src="{{ user_profile.picture.url }}">
	</div>

	<div>
		<a href="{% url 'users:followers' user_profile.username %}">Followers {{ followers }}</a>
		<a href="{% url 'users:following' user_profile.username %}">Following {{ following }}</a>
	</div>
	<div>
		<p>{{ user_profile.name }}</p>
		<p>{{ user_profile.username }}</p>
	</div>
	<div>
		<p>{{ user_profile.location }}</p>
	</div>
	<div>
		<p>{{ user_profile.blurb }}</p>
	</div>


	<div class="flip-container">
		<div class="flipper">
			<div class="front">
				<div>
					<img src="{{ user_profile.picture.url }}">
				</div>

				<div>
					<p>{{ user_profile.name }}</p>
					<p>{{ user_profile.username }}</p>
				</div>
				<div>
					<p>{{ user_profile.location }}</p>
				</div>
				<div>
					<p>{{ user_profile.blurb }}</p>
				</div>
			</div>
			<div class="back">

				<form action="{% url 'users:profile_update' %}" method="post">
					<!-- cross site request forgery protection -->
					{% csrf_token %}

					<div>
						<label>{{ form.name.label }}</label>
						{{ form.name }}
						{{ form.name.errors }}
					</div>
					<div>
						<label>{{ form.blurb.label }}</label>
						{{ form.blurb }}
						{{ form.blurb.errors }}
					</div>
					<div>
						<label>{{ form.location.label }}</label>
						{{ form.location }}
						{{ form.location.errors }}
					</div>

					<div>
						<label>{{ form.dob.label }}</label>
						{{ form.dob }}
						{{ form.dob.errors }}
					</div>

					<input id="id_submit" name="submit" type="submit" value="Save Changes">
				</form>
			</div>
		</div>
	</div>


{% endblock content %}

{% block page_js %}
	<!-- profile page javascript file -->
	<script src="{% static 'js/users/profile.js' %}"></script>
{% endblock page_js %}

ulo/templates/users/profile_update.html
{% extends "base.html" %}
{% load staticfiles i18n %}


{% block page_head %}
	<title>Profile Edit</title>
{% endblock page_head %}


{% block content %}
	<h1>Edit Profile Page</h1>

	{{ form.non_field_errors }}

	<a href="{% url 'users:profile' user.username %}">Back to profile</a>

	<form action="{% url 'users:profile_update' %}" method="post">
		<!-- cross site request forgery protection -->
		{% csrf_token %}

		<div>
			<label>{{ form.blurb.label }}</label>
			{{ form.blurb }}
			{{ form.blurb.errors }}
		</div>
		<div>
			<label>{{ form.location.label }}</label>
			{{ form.location }}
			{{ form.location.errors }}
		</div>

		<div>
			<label>{{ form.dob.label }}</label>
			{{ form.dob.0 }}
			{{ form.dob.errors }}

		</div>

		<input id="id_submit" name="submit" type="submit" value="Save Changes">
	</form>

{% endblock content %}

ulo/templates/users/signup.html
{% extends "base.html" %}
{% load staticfiles i18n %}


{% block page_head %}
	<title>Ulo Sign Up</title>
	<link href="{% static 'css/users/signup.css' %}" rel="stylesheet" type="text/css">
{% endblock page_head %}


{% block content %}
	<div id="signup_form_wrapper">

		<div id="signup_header">
			<h1 id="signup_title">Join Ulo</h1>
		</div>

		<div id="form_info">
		<span>It's free!</span>
		{% if form.non_field_errors %}
			<span class="icon error_icon"></span><!--
			--><p class="nonfield">{{ form.non_field_errors.0 }}</p>	
		{% endif %}
		</div>

		<form id="signup_form" action="{% url 'signup' %}" method="post">
			<!-- cross site request forgery protection -->
			{% csrf_token %}

			{{ form.d }}

			<div id="name_container">
				{{ form.name.errors }}
				<div>{{ form.name }}</div>
			</div>

			<div id="username_container">
				{{ form.name.errors }}
				<div id="username_field_container" class="">
					{{ form.username }}
					<span class="availability_text hide"></span>
					<span class="availability_icon"></span>
				</div>
			</div>

			<div id="email_container">
				{{ form.email.errors }}
				<div>{{ form.email }}</div>
			</div>

			<div id="password_container">
				{{ form.password.errors }}
				<div>{{ form.password }}</div>
			</div>

			<div id="select_fields">
				<div id="dob_container">
					<label class="dob_label" for="dob_select_container">{{ form.dob.label }}</label>
					<span class="private_icon"></span>
					<div id="dob_select_container">
						{{ form.dob.errors }}
						<div id="id_dob">{{ form.dob }}</div>
					</div>
				</div>

				<div id="gender_container">
					<label for="id_gender">{{ form.gender.label }}</label>
					<span class="private_icon"></span>
					<div id="gender_select_container">
						{{ form.gender.errors }}
						{{ form.gender }}
					</div>
				</div>
			</div>

			<div id="submit_container">
				<input id="id_submit" name="submit" type="submit" value="Sign Up">
			</div>
		</form>

		<div id="tc">
			<p class="tc_text">
				By joining SiteName, you agree to our <a href="#">Terms of Service</a> and <a href="#">Privacy Policy</a> including <a href="#">Cookie Use</a>
			</p>
		</div>

	</div>

{% endblock content %}

{% block page_js %}
	<script src="{% static 'js/users/signup.js' %}"></script>
{% endblock page_js %}