ulo/accounts/urls.py
"""
Accounts URL Configuration
The `urlpatterns` list routes URLs to views.
"""
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------
# standard library imports
from __future__ import unicode_literals

# core django imports
from django.conf.urls import include, url

# thrid party app imports

# project imports
from . import views

# ----------------------------------------------------------------------------------------


urlpatterns = [

	# Email verification
	url(r'^verification/(?P<token>[^<>\'"@]+)/$',
		views.EmailVerificationView.as_view(), name='verification'),
	url(r'^resend_verification/$',
		views.ResendEmailVerificationView.as_view(), name='resend_verification'),

	# Password reset
	url(r'^password_reset/$', 
		views.UserAccountView.as_view(), name='user_account'),
	url(r'^password_reset/email/$', 
		views.PasswordResetEmailView.as_view(), name='password_reset_email'),
	url(r'^password_reset/sent/$', 
		views.PasswordResetSentView.as_view(), name='password_reset_sent'),
	url(r'^password_reset/(?P<token>[^<>\'"@]+)/$',
		views.PasswordResetFormView.as_view(), name='password_reset_form'),

	url(r'^not_my_account/confirmed/$',
		views.NotMyAccountConfirmedView.as_view(), name='not_my_account_confirmed'),
	url(r'^not_my_account/not_registered/$',
		views.NotMyAccountNoUserView.as_view(), name='not_my_account_no_user'),
	url(r'^not_my_account/(?P<token>[^<>\'"@]+)/$',
		views.NotMyAccountView.as_view(), name='not_my_account'),
	

	# Token expired
	url(r'^expired/$', 
		views.LinkExpiredView.as_view(), name='expired'),
	# Account deactivated
	url(r'^deactivated/$', 
		views.DeactivatedAccountView.as_view(), name='deactivated'),
]

# ----------------------------------------------------------------------------------------

ulo/config/urls.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------
# standard library imports

# core django imports
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

# thrid party app imports

# project imports
from generics.views import HomeView, NavigationView,  SearchView
from users.views import LoginView, LogoutView, SignUpView


# TO SERVE MEDIA FILE IN DEVELOPMENT ONLY
from django.conf.urls.static import static


# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Landing Page
	url(r'^$', HomeView.as_view(), name='home'),
	# Search Page
	url(r'^search/$', SearchView.as_view(), name='search'),
	url(r'^search/', include('generics.urls', namespace='generics')),


	# User Posts (Post detail, Post form)
	url(r'^post/', include('posts.urls', namespace='posts')),
	# User Pages (Profile, Profile update)
	url(r'^user/', include('users.urls', namespace='users')),
	# User Comments
	url(r'^comment/', include('comments.urls', namespace='comments')),

	# Sign Up Page
	url(r'^signup/$', SignUpView.as_view(), name='signup'),
	# Login Page
	url(r'^login/(\?redirect_to=(?P<redirect_to>[^<>\'"@]*/))?$', 
		LoginView.as_view(), name='login'),
	# Logout Url
	url(r'^logout/$', LogoutView.as_view(), name='logout'),
	
	# Accounts Settings
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
	# User Settings
	url(r'^settings/', include('settings.urls', namespace='settings')),

	# Admin web interface
	url(r'^admin/', include(admin.site.urls)),

	# Error views
	url(r'^500/$', 'django.views.defaults.server_error', name='server_error'),

	# Dedicated site navigation when js is disabled.
	url(r'^navigation/$', NavigationView.as_view(), name='navigation'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ----------------------------------------------------------------------------------------

ulo/posts/urls.py
"""
Accounts URL Configuration
The `urlpatterns` list routes URLs to views.
"""
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------
# standard library imports
from __future__ import unicode_literals

# core django imports
from django.conf.urls import include, url

# thrid party app imports

# project imports
from . import views

# ----------------------------------------------------------------------------------------


urlpatterns = [

	# Post Form
	url(r'^$', views.PostFormView.as_view(), name='form'),
	# post only requests for videos
	url(r'^video/$', views.PostVideoFormView.as_view(), name='video_form'),

	url(r'^all/$', views.PostListView.as_view(), name='test'),

	# Users Post
	url(r'^(?P<pk>[\d]+)/$', views.PostView.as_view(), name='post'),
	url(r'^(?P<pk>[\d]+)/edit/$', views.PostEditView.as_view(), name='post_edit'),

	# Vote on a post
	url(r'^vote/$', views.PostVoteView.as_view(), name='vote'),


	# Post actions menu when JS is disabled
	url(r'^(?P<pk>[\d]+)/actions/$', views.PostActionsView.as_view(), name='actions'),
	# User reporting issue with post
	url(r'^report/complete/$', views.PostReportCompleteView.as_view(), name='report_complete'),
	url(r'^report/(?P<pk>[\d]+)/$', views.PostReportView.as_view(), name='report'),


]

# ----------------------------------------------------------------------------------------

ulo/settings/urls.py
"""
Settings URL Configuration
The `urlpatterns` list routes URLs to views.
"""
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------
# standard library imports
from __future__ import unicode_literals

# core django imports
from django.conf.urls import include, url

# thrid party app imports

# project imports
from . import views

# ----------------------------------------------------------------------------------------


urlpatterns = [

	url(r'^account/$',
		views.AccountSettingsView.as_view(), name='account'),
	url(r'^deactivate/$',
		views.DeactivateAccountView.as_view(), name='deactivate'),

	url(r'^password/$',
		views.PasswordSettingsView.as_view(), name='password'),

	url(r'^notifications/$',
		views.NotificationSettingsView.as_view(), name='notifications'),
]

# ----------------------------------------------------------------------------------------

ulo/accounts/models.py
from django.db import models

# Create your models here.

ulo/settings/models.py
from django.db import models

# Create your models here.

ulo/accounts/views.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------
# standard library imports
from __future__ import unicode_literals
import re

# core django imports
from django.contrib import messages
from django.contrib.auth import get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import Http404
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.cache import never_cache

# thrid party app imports

# project imports
from .forms import NewPasswordForm, NotMyAccountForm
from .sessions import BeginPasswordReset, EmailPasswordReset, endPasswordReset
from emails.emails import verify_email
from ulo.sessions import LinkViewsSession
from ulo.tokens import(
	GenericTokenGenerator, ResetPasswordTokenGenerator, VerifyEmailTokenGenerator
)
from ulo.utils import get_referer_path
from ulo.views import UloView, UloFormView, UloUpdateView
from ulo.viewmixins import LogoutRequiredMixin

# ----------------------------------------------------------------------------------------

def redirect_to_expired():
	return redirect(reverse('accounts:expired'))

def redirect_to_start():
	return redirect(reverse('accounts:user_account'))

class LinkExpiredView(UloView):
	template_name = 'accounts/expired.html'
	def get(self, request, *args, **kwargs):
		return render(request, self.template_name, {})

# ----------------------------------------------------------------------------------------

class DeactivatedAccountView(UloView):
	"""
	Display page informing the user that their account has been deactivated.
	"""
	template_name = 'accounts/deactivated.html'

# ----------------------------------------------------------------------------------------

class NotMyAccountView(UloUpdateView):

	form_class = NotMyAccountForm
	template_name = 'accounts/not_my_account.html'
	success_url = reverse_lazy('accounts:not_my_account_confirmed')
	user = None

	def redirect_token(self, token):
		try:
			self.user = GenericTokenGenerator().check_token(
				string=token, salt='not_my_account', fail_silently=False, 
				max_age=864000 # 10 days
			)
			if self.user.email_confirmed or \
				self.user.block_type == self.user.NOT_MY_ACCOUNT:
				raise ValueError

			email = re.sub(
				r'^([^@]{1,2})[^@]*(@[^.]{1,2}).*(\.[^.]*)$', r'\1******\2******\3', 
				self.user.email
			)

			self.context = {'username': self.user.name, 'email':email}
			# have caller return a response
			return None

		except get_user_model().DoesNotExist:
			# user does not exist
			LinkViewsSession(self.request).set('not_my_account_no_user', True)
			return redirect(reverse('accounts:not_my_account_no_user'))
		except Exception:
			# invalid token
			return redirect_to_expired()


	def get(self, request, token, *args, **kwargs):		
		return self.redirect_token(token) or \
			super(NotMyAccountView, self).get(request, *args, **kwargs)

	def post(self, request, token, *args, **kwargs):
		return self.redirect_token(token) or \
			super(NotMyAccountView, self).post(request, *args, **kwargs)

	def get_object(self):
		return self.user

	def form_valid(self, form):
		form.save()
		LinkViewsSession(self.request).set('not_my_account', True)
		return super(NotMyAccountView, self).form_valid(form)

# ----------------------------------------------------------------------------------------

class NotMyAccountNoUserView(UloView):

	template_name = 'accounts/not_my_account_no_user.html'

	def get(self, request, *args, **kwargs):
		if LinkViewsSession(request).get('not_my_account_no_user'):
			return super(NotMyAccountNoUserView, self).get(request, *args, **kwargs)
		raise Http404()

# ----------------------------------------------------------------------------------------

class NotMyAccountConfirmedView(UloView):

	template_name = 'accounts/not_my_account_confirmed.html'

	def get(self, request, *args, **kwargs):
		if LinkViewsSession(request).get('not_my_account'):
			return super(NotMyAccountConfirmedView, self).get(request, *args, **kwargs)
		raise Http404()
	
# ----------------------------------------------------------------------------------------

@method_decorator(never_cache, name='get')
# TO DO: MAKE USER LOG IN BEFORE SETTING CONFIRMATION AND THEN DISPLAY A FLASH MESSAGE
class EmailVerificationView(LoginRequiredMixin, UloView):
	"""
	Check that the token is valid and set is_confirmed to True, else display error
	message to user informing them that the token is no longer valid
	"""
	redirect_field_name = 'redirect_to'
	
	def get(self, request, token, *args, **kwargs):

		user = VerifyEmailTokenGenerator().check_token(
			string=token, salt='email_verification', max_age=604800 # 7 days
		)

		if user:
			if request.user.is_authenticated() and request.user != user:
				messages.info(request, _(
					'Please sign is as %(username)s to confirm your email address.'
					) % {'username':user.username}
				)
			else:
				user.email_confirmed = True;
				user.save()
				messages.success(request, 
					_('Thank you for confirming your email address!')
				)

			return redirect(reverse('home'))

		# redirect to error page
		return redirect_to_expired()

# ----------------------------------------------------------------------------------------

class ResendEmailVerificationView(LoginRequiredMixin, UloView):
	"""
	Check that the token is valid and set is_confirmed to True, else display error
	message to user informing them that the token is no longer valid
	"""

	def get(self, request, *args, **kwargs):
		raise Http404()


	def post(self, request, *args, **kwargs):

		if verify_email(request.user):
			messages.success(request, 
				_('We have sent you a confirmation email.'), extra_tags="flash"
			)
		else:
			messages.error(request, 
				_('We failed to send you a confirmation email. Please try again later.'),
				extra_tags="flash"
			)

		return redirect( get_referer_path(request) )

# ----------------------------------------------------------------------------------------

class UserAccountView(LogoutRequiredMixin, UloFormView):
	"""
	Start the password reset process, diplaying the user with a form to find their
	account.
	"""

	template_name = 'accounts/user_account.html'
	success_url = reverse_lazy('accounts:password_reset_email')
	form_class = BeginPasswordReset

	def get_form_kwargs(self):
		kwargs = super(UserAccountView, self).get_form_kwargs()
		kwargs.update({'request': self.request })
		return kwargs

# ----------------------------------------------------------------------------------------

class PasswordResetEmailView(UloView):
	"""
	Display some account information to the user and provide them with the option to
	send themselves a password reset email or cancel.
	"""
	template_name = 'accounts/password_reset_email.html'
	session = EmailPasswordReset

	def get_response(self, request, context=None, *args, **kwargs):		
		if context is None:
			return redirect_to_start()
		# AjaxRequestMixin context: add context to template through UloView
		self.context = context
		return super(PasswordResetEmailView, self).get(request, *args, **kwargs)

	def get(self, request, *args, **kwargs):
		context = self.session(request, True).get_request()
		return self.get_response(request, context, *args, **kwargs)

	def post(self, request, *args, **kwargs):

		session = self.session(request, True)

		if session.post_request(request.POST) is True:
			return redirect(reverse('accounts:password_reset_sent'))
			
		context = session.context()
		return self.get_response(request, context, *args, **kwargs)

# ----------------------------------------------------------------------------------------

class PasswordResetSentView(UloView):
	"""
	End the password reset process and display a page informing the user that an email
	has been sent to them.
	"""
	template_name = 'accounts/password_reset_sent.html'

	def get(self, request, *args, **kwargs):
		if endPasswordReset(request):
			return render(request, self.template_name, {})
		return redirect(reverse('accounts:password_reset_email'))

# ----------------------------------------------------------------------------------------

class PasswordResetFormView(LogoutRequiredMixin, UloFormView):
	"""
	Check the password reset token and diplay a change password form to the user.
	"""

	user = None
	form_class = NewPasswordForm
	success_url = reverse_lazy('home')
	template_name = 'accounts/password_reset_form.html'
	
	def get_form(self):
		return self.get_form_class()(self.user, **self.get_form_kwargs())

	def valid_token(self, token):
		if token:
			self.user = ResetPasswordTokenGenerator().check_token(
				string=token, salt='password_reset', max_age=1800
			)
			if self.user:
				self.context = {'name': self.user.name, 'src':self.user.picture.url}
				return True

		return False

	def get(self, request, token, *args, **kwargs):
		if self.valid_token(token):
			return super(PasswordResetFormView, self).get(request, *args, **kwargs)
		return redirect_to_expired()

	def post(self, request, token, *args, **kwargs):
		if self.valid_token(token):
			return super(PasswordResetFormView, self).post(request, *args, **kwargs)
		return redirect_to_expired()

	def form_valid(self, form):
		user = form.save()
		if user:
			login(self.request, user)
		return super(PasswordResetFormView, self).form_valid(form)

# ----------------------------------------------------------------------------------------

ulo/templates/settings/account.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}
  <h1>Account Settings</h1>

  {{ account_form.non_field_errors }}

  <form id="settings_form" action="{% url 'settings:account' %}" method="post">
      <!-- cross site request forgery protection -->
      {% csrf_token %}


      {{account_form.is_confirmed}}

      <div>
        {{ account_form.name.label }}
        {{ account_form.name }}
        {{ account_form.name.errors }}
      </div>

      <div>
        {{ account_form.username.label }}
        {{ account_form.username }}
        {{ account_form.username.errors }}
      </div>

      <div>
        {{ account_form.email.label }}
        {{ account_form.email }}
        {{ account_form.email.errors }}
        {% if not user.email_confirmed %}
          <p>Check your email to confirm your address</p>
          <a href="accounts:resend_verification">Resend Email Confirmation</a>
        {% endif %}
      </div>



      <div>
        {{ account_form.password.label }}
        {{ account_form.password }}
        {{ account_form.password.errors }}
        <input type="submit"  value="Save Changes">
      </div>
        
      </div>

    
  </form>

  <div>
    <a href="{% url 'settings:deactivate' %}">Deactivate Account</a>
  </div>
{% endblock content %}

ulo/templates/settings/deactivate.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}
  <h1>We are sad to see you go!</h1>

  <p>Remember, you can reactivate your account by logging in within 30 days. After 30 days your account will be removed permanently.</p>


  {{ account_form.non_field_errors }}

  <form id="settings_form" action="{% url 'settings:deactivate' %}" method="post">
      <!-- cross site request forgery protection -->
      {% csrf_token %}
     <input type="submit" name="submit" value="Deactivate">
     <input type="submit" name="cancel" value="Cancel">
  </form>
{% endblock content %}

ulo/templates/settings/notifications.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}
  <h1>Notification Settings</h1>

  {% firstof notifications_form.non_field_errors notifications_form.errors notifications_form.success %}

  <form action="{% url 'settings:notifications' %}" method="post">
      <!-- cross site request forgery protection -->
      {% csrf_token %}

      <div>
        {{ notifications_form.is_active.label }}
        {{ notifications_form.is_active }}
      </div>
      <div>
        {{ notifications_form.is_verified.label }}
        {{ notifications_form.is_verified }}
      </div>
      <div>
        {{ notifications_form.email_confirmed.label }}
        {{ notifications_form.email_confirmed }}
      </div>
      <div>
        {{ notifications_form.block_type.label }}
        {{ notifications_form.block_type }}
      </div>
        <input type="submit"  value="Save Changes">
      </div>

    
  </form>
{% endblock content %}

ulo/templates/settings/password.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}
  <h1>Password Settings</h1>

  {{ password_form.non_field_errors }}
  {% firstof password_form.new_password1.errors password_form.new_password2.errors password_form.password.errors %}

  <form action="{% url 'settings:password' %}" method="post">
      <!-- cross site request forgery protection -->
      {% csrf_token %}


      

      <div>
        {{ password_form.password.label }}
        {{ password_form.password }}
      </div>
      <div>
        <a href="{% url 'accounts:password_reset_email' %}">Forgotten your password?</a>
      </div>

      <div>
        {{ password_form.new_password1.label }}
        {{ password_form.new_password1 }}
      </div>

      <div>
        {{ password_form.new_password2.label }}
        {{ password_form.new_password2 }}
      </div>

        <input type="submit"  value="Change password">
      </div>

    
  </form>
{% endblock content %}

ulo/templates/settings/sidebar.html
<div>
	Menu
</div>